version: '3'
services:
  db:
    image: postgres:alpine
    restart: always
    container_name: challenge-api-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - app_challenge_api_network

networks:
  app_challenge_api_network:

volumes:
  postgres-db:
